apiVersion: apps/v1
kind: Deployment
metadata:
  createionTimestamp: null
  labels:
    app: dep-of-out-app-1
  name: dep-of-out-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      finder: out-app-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        finder: out-app-1
    spec:
      containers:
        - image: tasdidur/client-go-out-app-1
          name: container-out-app-1